name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Vienna
          plugin_languages: yes
          # plugin_languages_indepth: yes
          # commits_authoring: Rakantor
          # plugin_languages_details: percentage, lines
          plugin_languages_limit: 7
          plugin_languages_other: yes
          plugin_languages_ignored: lua
          plugin_languages_skipped: lowlighter/metrics, Rakantor/cors-anywhere, Rakantor/fedora-workstation-configs, Rakantor/mint-cinnamon-configs, Rakantor/StreamSaver.js, Rakantor/WanaKana
